name: napari_standalone
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _libavif_api=1.1.1=h57928b3_2
  - _openmp_mutex=4.5=2_gnu
  - alabaster=1.0.0=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - aom=3.9.1=he0c23c2_0
  - app-model=0.3.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asciitree=0.3.3=py_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=24.3.0=py310haa95532_0
  - babel=2.16.0=py310haa95532_0
  - blosc=1.21.3=h6c2663c_0
  - bottleneck=1.4.2=py310hc99e966_0
  - brotli=1.0.9=h827c3e9_9
  - brotli-bin=1.0.9=h827c3e9_9
  - brotli-python=1.0.9=py310h5da7b33_9
  - bzip2=1.0.8=h2bbff1b_6
  - c-blosc2=2.12.0=h2f4ed9d_0
  - ca-certificates=2024.12.31=haa95532_0
  - cachey=0.2.1=pyh9f0ad1d_0
  - certifi=2024.12.14=py310haa95532_0
  - cffi=1.17.1=py310h827c3e9_1
  - cfitsio=3.470=h2bbff1b_7
  - charls=2.2.0=h6c2663c_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh7428d3b_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.2.2=pyhd8ed1ab_1
  - cpython=3.10.16=py310hd8ed1ab_1
  - cytoolz=1.0.1=py310h827c3e9_0
  - dask-core=2024.12.1=py310haa95532_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.11=py310h5da7b33_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - deprecated=1.2.15=pyhd8ed1ab_1
  - docstring_parser=0.16=pyhd8ed1ab_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h8ddb27b_0
  - fasteners=0.19=pyhd8ed1ab_1
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - freetype=2.12.1=ha860e81_0
  - freetype-py=2.5.1=pyhd8ed1ab_1
  - giflib=5.2.2=h7edc060_0
  - glib=2.78.4=hd77b12b_0
  - glib-tools=2.78.4=hd77b12b_0
  - gst-plugins-base=1.22.3=hfc3ed34_1
  - gstreamer=1.22.3=h1779075_1
  - h2=4.1.0=pyhd8ed1ab_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - hpack=4.0.0=py_0
  - hsluv=5.0.4=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd3eb1b0_0
  - icu=73.1=h6c2663c_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs=2024.9.22=py310hacb3832_0
  - imageio=2.36.1=pyh12aca89_1
  - imagesize=1.4.1=py310haa95532_0
  - importlib-metadata=8.5.0=py310haa95532_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - in-n-out=0.2.1=pyhd8ed1ab_1
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=py310haa95532_0
  - ipython=8.31.0=pyh7428d3b_0
  - jedi=0.19.2=py310haa95532_0
  - jinja2=3.1.5=pyhd8ed1ab_0
  - jpeg=9e=h827c3e9_3
  - jsonschema=4.23.0=py310haa95532_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=py310haa95532_0
  - jxrlib=1.1=he774522_2
  - kiwisolver=1.4.8=py310h5da7b33_0
  - krb5=1.20.1=h5b6d351_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=py310haa95532_0
  - lcms2=2.16=hb4a4139_0
  - lerc=4.0.0=h5da7b33_0
  - libaec=1.1.3=hcdb6601_0
  - libavif=1.1.1=h4d049a7_2
  - libavif16=1.1.1=h4d049a7_2
  - libblas=3.9.0=26_win64_mkl
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcblas=3.9.0=26_win64_mkl
  - libclang=14.0.6=default_hb5a9fac_2
  - libclang13=14.0.6=default_h8e68704_2
  - libdeflate=1.22=h5bf469e_0
  - libexpat=2.6.4=he0c23c2_0
  - libffi=3.4.4=hd77b12b_1
  - libgcc=14.2.0=h1383e82_1
  - libglib=2.78.4=ha17d25a_0
  - libgomp=14.2.0=h1383e82_1
  - libhwloc=2.11.2=default_ha69328c_1001
  - libhwy=1.0.7=h91493d7_0
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libjxl=0.8.2=h0c5eeff_0
  - liblapack=3.9.0=26_win64_mkl
  - liblzma=5.6.3=h2466b09_1
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.2=h70ee33d_0
  - libsodium=1.0.18=h62dcd97_0
  - libsqlite=3.48.0=h67fdade_0
  - libtiff=4.5.1=h44ae7cf_1
  - libvorbis=1.3.7=he774522_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.5=h24da03e_0
  - libzlib=1.2.13=h2466b09_6
  - libzopfli=1.0.3=ha925a31_0
  - llvmlite=0.43.0=py310hf2fb9eb_1
  - locket=1.0.0=py310haa95532_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=2.1.3=py310h827c3e9_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2024.2.2=h66d3029_15
  - msgpack-python=1.0.3=py310h59b6b97_0
  - napari-base=0.5.5=pyh9208f05_0
  - napari-console=0.1.3=pyh73487a3_0
  - napari-plugin-engine=0.2.0=pyha07c04f_3
  - napari-plugin-manager=0.1.4=pyha07c04f_0
  - napari-svg=0.2.1=pyha07c04f_0
  - nest-asyncio=1.6.0=py310haa95532_0
  - networkx=3.4.2=py310haa95532_0
  - npe2=0.7.7=pyhd8ed1ab_1
  - numba=0.60.0=py310h5da7b33_0
  - numcodecs=0.12.1=py310h3469f8a_0
  - numexpr=2.10.2=mkl_py310h11de614_0
  - numpy=1.26.4=py310hf667824_0
  - numpydoc=1.8.0=pyhd8ed1ab_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.4.0=ha4e3fda_1
  - packaging=24.2=py310haa95532_0
  - pandas=2.2.3=py310h5da7b33_0
  - parso=0.8.4=py310haa95532_0
  - partd=1.4.2=py310haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.0.0=py310h096bfcc_1
  - pint=0.24.4=pyhd8ed1ab_1
  - pip=24.2=py310haa95532_0
  - pkgutil-resolve-name=1.3.10=py310haa95532_1
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - ply=3.11=py310haa95532_0
  - pooch=1.8.2=py310haa95532_0
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=5.9.0=py310h827c3e9_1
  - psygnal=0.11.1=pyhd8ed1ab_1
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyconify=0.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic-compat=0.1.2=pyhd8ed1ab_0
  - pydantic-core=2.27.2=py310hc226416_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyopengl=3.1.6=pyhd8ed1ab_2
  - pyproject_hooks=1.2.0=pyhd8ed1ab_1
  - pyqt=5.15.10=py310h5da7b33_1
  - pyqt5-sip=12.13.0=py310h827c3e9_1
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.16=h4607a30_1
  - python-build=1.2.2.post1=py310haa95532_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-dotenv=1.0.1=pyhd8ed1ab_1
  - python-tzdata=2024.2=pyhd8ed1ab_1
  - python_abi=3.10=2_cp310
  - pytz=2024.1=py310haa95532_0
  - pywavelets=1.8.0=py310h827c3e9_0
  - pywin32=308=py310h5da7b33_0
  - pyyaml=6.0.2=py310h827c3e9_0
  - pyzmq=26.2.0=py310h5da7b33_0
  - qt-main=5.15.2=h19c9488_11
  - qtconsole-base=5.6.1=pyha770c72_1
  - qtpy=2.4.2=pyhd8ed1ab_1
  - rav1e=0.6.6=h975169c_2
  - referencing=0.36.1=pyhd8ed1ab_0
  - requests=2.32.3=py310haa95532_1
  - rich=13.9.4=py310haa95532_0
  - rpds-py=0.22.3=py310h636fa0f_0
  - scikit-image=0.24.0=py310hc64d2fc_0
  - scipy=1.15.1=py310h164493e_0
  - setuptools=75.1.0=py310haa95532_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - sip=6.7.12=py310h5da7b33_1
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=hcdb6601_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sphinx=8.1.3=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=py310haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - superqt=0.7.0=pyhb6d5dde_0
  - svt-av1=2.3.0=he0c23c2_0
  - tabulate=0.9.0=py310haa95532_0
  - tbb=2021.13.0=h62715c5_1
  - tifffile=2024.12.12=py310haa95532_0
  - tk=8.6.14=h0416ee5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.2.1=pyhd8ed1ab_1
  - tomli-w=1.2.0=pyhd8ed1ab_0
  - toolz=1.0.0=py310haa95532_0
  - tornado=6.4.2=py310h827c3e9_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py310haa95532_0
  - typer=0.15.1=pyhd8ed1ab_0
  - typer-slim=0.15.1=pyhd8ed1ab_0
  - typer-slim-standard=0.15.1=hd8ed1ab_0
  - typing-extensions=4.12.2=py310haa95532_0
  - typing_extensions=4.12.2=py310haa95532_0
  - tzdata=2024b=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_1
  - urllib3=2.3.0=py310haa95532_0
  - vc=14.40=haa95532_2
  - vc14_runtime=14.42.34433=he29a5d6_23
  - vispy=0.14.3=py310hb0944cc_1
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.44.0=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wrapt=1.17.0=py310h827c3e9_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - yaml=0.2.5=he774522_0
  - zarr=2.13.3=py310haa95532_0
  - zeromq=4.3.5=hd77b12b_0
  - zfp=1.0.1=he0c23c2_2
  - zipp=3.21.0=py310haa95532_0
  - zlib=1.2.13=h2466b09_6
  - zlib-ng=2.0.7=h2bbff1b_0
  - zstandard=0.23.0=py310h4fc1ca9_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - ansicon==1.89.0
      - anyio==4.8.0
      - arrow==1.3.0
      - av==14.0.1
      - beautifulsoup4==4.12.3
      - blessed==1.20.0
      - boto3==1.36.3
      - botocore==1.36.3
      - croniter==1.3.15
      - dask-expr==1.1.21
      - dask-image==2024.5.3
      - dateutils==0.6.12
      - deepdiff==7.0.1
      - editor==1.6.6
      - fastapi==0.88.0
      - filelock==3.17.0
      - frozenlist==1.5.0
      - fsspec==2023.12.2
      - h11==0.14.0
      - imageio-ffmpeg==0.6.0
      - inquirer==3.4.0
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jinxed==1.3.0
      - jmespath==1.0.1
      - jupyterlab-widgets==3.0.13
      - lightning==2.0.1
      - lightning-cloud==0.5.70
      - lightning-utilities==0.11.9
      - magicgui==0.2.5
      - mpmath==1.3.0
      - multidict==6.1.0
      - napari==0.4.5
      - ordered-set==4.1.0
      - pims==0.7
      - propcache==0.2.1
      - protobuf==5.29.3
      - pyarrow==19.0.0
      - pydantic==1.10.21
      - pyjwt==2.10.1
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.0.post0
      - readchar==4.2.1
      - runs==1.2.2
      - s3transfer==0.11.1
      - slicerator==1.1.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - starlette==0.22.0
      - starsessions==1.3.0
      - sympy==1.13.1
      - torch==2.5.1
      - torchmetrics==1.6.1
      - types-python-dateutil==2.9.0.20241206
      - uvicorn==0.34.0
      - websocket-client==1.8.0
      - websockets==11.0.3
      - widgetsnbextension==4.0.13
      - xmod==1.8.1
      - yarl==1.18.3
prefix: C:\ProgramData\anaconda3\envs\napari_standalone