name: gecko-napari
channels:
  - conda-forge    
dependencies:
  - python=3.11
  - ipython
  - ipykernel
  - jupyterlab
  - numpy
  - pandas
  - imageio
  - dask
  - dask-image
  - napari=0.5.6      
  - pyqt
  - magicgui
  - ipywidgets
  - qtpy
  - pip
  - pip:
      - "imageio[ffmpeg]"
